
spring:
  main:
    banner-mode: "off"
  data:
    mongodb:
      auto-index-creation: true
      database: webflux-db
      uri: mongodb://backend:secret@localhost:27017/admin
  application:
    name: webflux
  profiles:
    active: dev